+*In[33]:*+
[source, ipython3]
----
1


----


+*Out[33]:*+
----1----


+*In[6]:*+
[source, ipython3]
----
print ('p')
----


+*Out[6]:*+
----
p
----


+*In[9]:*+
[source, ipython3]
----
gt = 'hello mai'
print (gt)

----


+*Out[9]:*+
----
hello mai
----


+*In[12]:*+
[source, ipython3]
----
print ('Привет, эта программа считает сумму двух чисел')
print ('Привет, эта программа считает сумму двух чисел')
print ('Привет, эта программа считает сумму двух чисел')
a = input ()
b = input ()
c=a+b
print (c)
----


+*Out[12]:*+
----
Привет, эта программа считает сумму двух чисел
Привет, эта программа считает сумму двух чисел
Привет, эта программа считает сумму двух чисел
2
3
23
----


+*In[13]:*+
[source, ipython3]
----
print ('Привет, эта программа считает сумму двух чисел')
print ('Привет, эта программа считает сумму двух чисел')
print ('Привет, эта программа считает сумму двух чисел')
a = input ()
b = input ()
c=a+b
print (c)

----


+*Out[13]:*+
----
Привет, эта программа считает сумму двух чисел
Привет, эта программа считает сумму двух чисел
Привет, эта программа считает сумму двух чисел
23
45
2345
----


+*In[21]:*+
[source, ipython3]
----
a=100
b=3
print (a+b) # сложение
print (a-b) # вычитание
print (a*b) # умножение
print (a/b) # деление
print (a%b) # остаток от делаения
print (a//b) # целая часть от деления
print (1.2 - 1.0) # выводит странное значение
----


+*Out[21]:*+
----
103
97
300
33.333333333333336
1
33
0.19999999999999996
----


+*In[ ]:*+
[source, ipython3]
----
a = none # пустота.нет значений 

----


+*In[24]:*+
[source, ipython3]
----
t = True
f = False
print (False)
print(bool(0))

type (t)
----


+*Out[24]:*+
----
False
False
bool----


+*In[29]:*+
[source, ipython3]
----
type(1e-5)
int(1e-5)
----


+*Out[29]:*+
----0----


+*In[34]:*+
[source, ipython3]
----
ar = [1,2,3,4,5,6,7,8,9]
print (ar)
print (ar[1])
print (ar[0:4])
print (ar[0:4:2])
print (ar[::-1])

print(ar.count(1))
print(len(ar))

----


+*Out[34]:*+
----
[1, 2, 3, 4, 5, 6, 7, 8, 9]
2
[1, 2, 3, 4]
[1, 3]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
1
9
----


+*In[39]:*+
[source, ipython3]
----
tple = 1, 2
a, b = tple
#a, *b = tple
print(a)
print(b)
----


+*Out[39]:*+
----
1
2
----


+*In[40]:*+
[source, ipython3]
----
a = True

b = False

a and b
----


+*Out[40]:*+
----False----


+*In[41]:*+
[source, ipython3]
----
(a and b) or b

----


+*Out[41]:*+
----False----


+*In[42]:*+
[source, ipython3]
----
(a and b) or not (a and b)

----


+*Out[42]:*+
----True----


+*In[43]:*+
[source, ipython3]
----
a and b or not (a or b) or b

----


+*Out[43]:*+
----False----


+*In[44]:*+
[source, ipython3]
----
b and b or not a and (a or b or a) or not (a or b)

----


+*Out[44]:*+
----False----


+*In[45]:*+
[source, ipython3]
----
1 << 2

----


+*Out[45]:*+
----4----


+*In[46]:*+
[source, ipython3]
----
1 & 0 | 1 >> 1
----


+*Out[46]:*+
----0----


+*In[47]:*+
[source, ipython3]
----
1 & 0 | 1 >> 0


----


+*Out[47]:*+
----1----


+*In[48]:*+
[source, ipython3]
----
0b101 & 0b111 ^ 0b111 | 0b010 #Комментарий: "0b101" - запись числа "5" на языке Python в двоичном виде
----


+*Out[48]:*+
----2----


+*In[88]:*+
[source, ipython3]
----
one = 'Покупка'
few = 'Покупки'
many = 'Покупок'
n = int(input())
#Остаток от деления на 10 == 1, то one
#Остаток от деления на 10 == [2,4], то few
#Остаток от деления на 10 == 0 || 5,9, то many
if n % 10 == 1:
    print (one)
elif n % 10 in [2,3,4]:
    print (few)
elif n % 10 == 0 in [5,6,7,8,9,0]:
    print (many)
elif 9 < n % 100 < 20:
    print (many)
else: 
    print ('error')
----


+*Out[88]:*+
----
123
Покупки
----


+*In[ ]:*+
[source, ipython3]
----

----


+*In[ ]:*+
[source, ipython3]
----

----


+*In[ ]:*+
[source, ipython3]
----

----


+*In[ ]:*+
[source, ipython3]
----
10

----
